-- Generated by `pnpm d1:schema:dump` from the Kysely SQLite migrations. Do not edit.

CREATE TABLE "agent" (
          id TEXT NOT NULL,
          tenant_id TEXT NOT NULL,
          name TEXT NOT NULL,
          manifest BLOB NOT NULL,
          external_id TEXT,
          created_by_subject BLOB NOT NULL,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
          PRIMARY KEY (id),
          UNIQUE (tenant_id, name)
        ) STRICT
      ;

CREATE TABLE mcp_server (
        id TEXT NOT NULL,
        tenant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        manifest BLOB NOT NULL,
        oauth_server BLOB,
        oauth_client BLOB,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (id)
      ) STRICT
    ;

CREATE TABLE model_provider (
        tenant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        manifest BLOB NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (tenant_id, name)
      ) STRICT
    ;

CREATE TABLE oauth_pending_authorization (
        id TEXT NOT NULL,
        oauth_server_id TEXT NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
        user_id TEXT NOT NULL,
        auth_data BLOB NOT NULL,
        created_at TEXT NOT NULL,
        CONSTRAINT oauth_pending_authorization_pkey PRIMARY KEY (id)
      ) STRICT
    ;

CREATE TABLE oauth_token (
        oauth_server_id TEXT NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
        user_id TEXT NOT NULL,
        token BLOB NOT NULL,
        updated_at TEXT NOT NULL,
        CONSTRAINT oauth_token_pkey PRIMARY KEY (oauth_server_id, user_id)
      ) STRICT
    ;

CREATE TABLE sandbox_provider (
        tenant_id TEXT NOT NULL,
        manifest BLOB NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', status_reason TEXT, build_metadata BLOB,
        PRIMARY KEY (tenant_id)
      ) STRICT
    ;

CREATE TABLE "schedule" (
          id TEXT NOT NULL,
          tenant_id TEXT NOT NULL,
          agent_id TEXT NOT NULL,
          agent_name TEXT NOT NULL,
          name TEXT NOT NULL,
          manifest BLOB NOT NULL,
          status TEXT NOT NULL CHECK (length(status) <= 16),
          created_by_subject BLOB NOT NULL,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL,
          PRIMARY KEY (id),
          FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE
        ) STRICT
      ;

CREATE TABLE "schedule_run" (
          id TEXT NOT NULL,
          tenant_id TEXT NOT NULL,
          schedule_id TEXT NOT NULL REFERENCES "schedule" (id) ON DELETE CASCADE,
          name TEXT NOT NULL,
          scheduled_for TEXT NOT NULL,
          status TEXT NOT NULL CHECK (length(status) <= 16),
          created_by_subject BLOB NOT NULL,
          triggered_at TEXT,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL, reason TEXT,
          PRIMARY KEY (id)
        ) STRICT
      ;

CREATE TABLE "session" (
          tenant_id TEXT NOT NULL,
          session_id TEXT NOT NULL,
          created_by_subject BLOB NOT NULL,
          agent_id TEXT,
          agent_name TEXT,
          agent_spec BLOB,
          title TEXT,
          last_turn_id TEXT,
          external_id TEXT,
          custom BLOB,
          metadata BLOB NOT NULL DEFAULT (jsonb('{}')),
          metrics BLOB NOT NULL DEFAULT (jsonb('{"total_cost_in_usd":0,"total_duration_ms":0,"total_turns":0}')),
          last_activity_timestamp_ms INTEGER NOT NULL,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL, source BLOB,
          PRIMARY KEY (session_id),
          CHECK (
            (agent_id IS NOT NULL AND agent_spec IS NULL)
            OR (agent_id IS NULL AND agent_spec IS NOT NULL)
          )
        ) STRICT
      ;

CREATE TABLE session_event (
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        event_id TEXT NOT NULL,
        event BLOB NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (session_id, turn_id, event_id)
      ) STRICT
    ;

CREATE TABLE skill (
        tenant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        manifest BLOB NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (tenant_id, name)
      ) STRICT
    ;

CREATE TABLE thread_capability_state (
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        key TEXT NOT NULL,
        state BLOB,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (session_id, turn_id, thread_id, key)
      ) STRICT
    ;

CREATE TABLE thread_context_log (
        append_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        thread_id TEXT NOT NULL,
        turn_id TEXT NOT NULL,
        body BLOB NOT NULL,
        created_at TEXT NOT NULL
      ) STRICT
    ;

CREATE TABLE turn (
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        first_turn_id TEXT NOT NULL,
        previous_turn_id TEXT,
        ancestor_ids BLOB NOT NULL,
        input BLOB NOT NULL,
        state BLOB NOT NULL,
        checkpoint BLOB NOT NULL,
        custom BLOB,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (session_id, turn_id)
      ) STRICT
    ;

CREATE TABLE turn_thread (
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        checkpoint BLOB NOT NULL,
        agent_info BLOB,
        current_context_usage BLOB NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (session_id, turn_id, thread_id)
      ) STRICT
    ;

CREATE TABLE turn_thread_context (
        session_id TEXT NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        pos INTEGER NOT NULL,
        append_id INTEGER NOT NULL,
        PRIMARY KEY (session_id, turn_id, thread_id, pos)
      ) STRICT
    ;

CREATE INDEX agent_created_by_subject_id_idx
          ON agent (tenant_id, json_extract(created_by_subject, '$.subject_id'))
      ;

CREATE UNIQUE INDEX agent_external_id_uq
          ON agent (tenant_id, external_id)
          WHERE external_id IS NOT NULL
      ;

CREATE UNIQUE INDEX mcp_server_tenant_name_idx
        ON mcp_server (tenant_id, name)
    ;

CREATE INDEX schedule_agent_id_idx
          ON schedule (tenant_id, agent_id)
      ;

CREATE INDEX schedule_agent_idx
          ON schedule (tenant_id, agent_name)
      ;

CREATE INDEX schedule_created_by_subject_id_idx
          ON schedule (tenant_id, json_extract(created_by_subject, '$.subject_id'))
      ;

CREATE UNIQUE INDEX schedule_name_uq
          ON schedule (tenant_id, agent_name, name)
      ;

CREATE INDEX schedule_run_created_by_subject_id_idx
          ON schedule_run (tenant_id, json_extract(created_by_subject, '$.subject_id'))
      ;

CREATE INDEX schedule_run_list_idx
          ON schedule_run (schedule_id, scheduled_for DESC)
      ;

CREATE UNIQUE INDEX schedule_run_name_idx
          ON schedule_run (tenant_id, schedule_id, name)
      ;

CREATE UNIQUE INDEX schedule_run_pending_uq
          ON schedule_run (schedule_id)
          WHERE status = 'scheduled'
      ;

CREATE INDEX schedule_run_scheduled_for_idx
          ON schedule_run (scheduled_for)
          WHERE status = 'scheduled'
      ;

CREATE INDEX session_agent_created_at_idx
          ON session (tenant_id, agent_id, created_at)
          WHERE agent_id IS NOT NULL
      ;

CREATE INDEX session_agent_id_idx
          ON session (tenant_id, agent_id)
          WHERE agent_id IS NOT NULL
      ;

CREATE INDEX session_created_by_subject_id_idx
          ON session (tenant_id, json_extract(created_by_subject, '$.subject_id'))
      ;

CREATE UNIQUE INDEX session_external_id_uq
          ON session (tenant_id, external_id)
          WHERE external_id IS NOT NULL
      ;

CREATE INDEX session_list_idx
          ON session (tenant_id, created_at, session_id)
      ;

CREATE INDEX session_list_updated_at_idx
          ON session (tenant_id, updated_at, session_id)
      ;

CREATE INDEX session_source_idx
        ON session (tenant_id, json_extract(source, '$.type'), json_extract(source, '$.id'))
        WHERE source IS NOT NULL
    ;

CREATE INDEX thread_context_log_lookup_idx
        ON thread_context_log (session_id, thread_id, append_id)
    ;

CREATE INDEX turn_list_idx
        ON turn (session_id, created_at, turn_id)
    ;

CREATE INDEX turn_thread_context_append_idx
        ON turn_thread_context (session_id, thread_id, append_id)
    ;
