// Writes `worker-configuration.d.ts` from wrangler.jsonc, or with `--check` fails when the committed
// file is stale. An empty env file keeps a developer's local `.env` out of the generated `Env`.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const packageDir = path.resolve(import.meta.dirname, '..');
// Keep in step with the `workers:*` scripts in package.json.
const WRANGLER = 'wrangler@4.131.2';
const COMMITTED = 'worker-configuration.d.ts';
// Next to the committed file, so the generated relative imports match.
const CHECK_OUTPUT = 'worker-configuration.check.d.ts';
const BACKUP = 'worker-configuration.d.ts.bak';
const EMPTY_ENV = path.join('.wrangler', 'empty.env');
// These header lines carry the command, output path, hash, and workerd version, not the types.
const GENERATOR_HEADER = ['// Generated by Wrangler by running', '// Runtime types generated with'];

function typesBody(file) {
  return readFileSync(path.join(packageDir, file), 'utf8')
    .split(/\r?\n/)
    .filter(line => !GENERATOR_HEADER.some(prefix => line.startsWith(prefix)))
    .join('\n');
}

function generate(output) {
  const result = spawnSync('bunx', [WRANGLER, 'types', output, '--config=wrangler.jsonc', `--env-file=${EMPTY_ENV}`], {
    cwd: packageDir,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (result.error !== undefined) {
    console.error(`Could not run bunx ${WRANGLER}: ${result.error.message}`);
    return 1;
  }
  return result.status ?? 1;
}

function check() {
  try {
    const status = generate(CHECK_OUTPUT);
    if (status !== 0) {
      return status;
    }
    if (typesBody(CHECK_OUTPUT) !== typesBody(COMMITTED)) {
      console.error(`${COMMITTED} does not match wrangler.jsonc; run \`pnpm workers:types\` and commit the result.`);
      return 1;
    }
    return 0;
  } finally {
    rmSync(path.join(packageDir, CHECK_OUTPUT), { force: true });
  }
}

/**
 * Generates under the committed name, because wrangler records a non-default output path in the header.
 * The committed file waits aside (wrangler would otherwise skip a file whose header hash matches, keeping
 * a hand edit) and comes back if generation fails.
 */
function write() {
  const committed = path.join(packageDir, COMMITTED);
  const backup = path.join(packageDir, BACKUP);
  // A backup left by a killed run is the good file; the committed name may hold a partial one.
  if (existsSync(backup)) {
    renameSync(backup, committed);
  }
  const hadCommitted = existsSync(committed);
  if (hadCommitted) {
    renameSync(committed, backup);
  }
  const status = generate(COMMITTED);
  if (status === 0 && existsSync(committed)) {
    rmSync(backup, { force: true });
    return 0;
  }
  if (hadCommitted) {
    renameSync(backup, committed);
  }
  return status === 0 ? 1 : status;
}

function main() {
  mkdirSync(path.join(packageDir, '.wrangler'), { recursive: true });
  writeFileSync(path.join(packageDir, EMPTY_ENV), '');
  return process.argv.includes('--check') ? check() : write();
}

process.exitCode = main();
